codecov:
  notify:
    require_ci_to_pass: yes
language: node_js
scripts:
  - npm install codecov -g
after_success:
  - codecov
coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no